# Deploy 'Facility-CMS' (publish) as IIS website using release zip from S3
name: cd-deploy-iis

on:
  workflow_dispatch:
    inputs:
      build-release-runner:
        description: "Runner where the release build will run"
        type: string
        required: false
        default: "yasmin-machine-org"

      deployment-runner:
        description: "Runner label(s) to deploy to (separated by comma)"
        required: true

      target-version:
        description: "Version to deploy (if not of latest)"
        required: false
        default: "latest"

jobs:
  # ---------- JOB ----------
  build-release:
    uses: ./.github/workflows/cd-build-release.yml
    with:
      build-release-runner: ${{ inputs.build-release-runner }}

  deploy-iis:
    uses: Star-Communications/centralized-repo/.github/workflows/cd-deploy-iis.yml@master
    needs: build-release
    with:
      runs-on: ${{ inputs.deployment-runner }}
      target-version: ${{ inputs.target-version }}
      s3-bucket: "sc-releases-bucket"
      s3-prefix: "facility-cms"
      iis-website-name: "Facility"
    secrets:
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::977628787421:role/oidc-facility-cms-download-release-s3-role"
