# .pre-commit-hooks.yaml
- id: custom-formatter
  name: Custom Formatter
  description: Formats various code files according to standard rules.
  entry: hooks/custom_formatter.py
  language: system
  files: \.(cs|csproj|vue|js|html|css|yml|yaml|xml)$
