# .pre-commit-hooks.yaml
- id: custom-formatter
  name: Custom Formatter
  description: Formats various code files according to standard rules.
  entry: custom-formatter
  language: python
  types: [python]
  stages: [pre-commit, pre-merge-commit, manual]
  files: .*
