# Prepare build (release) files and upload to S3
name: cd-prepare-release

on:
  workflow_call:
    inputs:
      build-release-runner:
        description: "Runner that will build the project for the release"
        type: string
        required: true

  workflow_dispatch:
    inputs:
      build-release-runner:
        description: "Runner that will build the project for the release"
        type: string
        required: false
        default: "ubuntu-latest"

jobs:
  # ---------- JOB ----------
  pre-release-checks:
    uses: Star-Communications/centralized-repo/.github/workflows/cd-pre-release-checks.yml@master
    with:
      runs-on: ${{ inputs.build-release-runner }}
    # this job returns the following outputs: "is-new-release-job-output" (true/false)

  # ---------- JOB ----------
  build-release:
    runs-on: ${{ inputs.build-release-runner }}

    needs: pre-release-checks

    # skip building the project, if current commit already has a release in S3
    if: ${{ needs.pre-release-checks.outputs.is-new-release-job-output == 'true' }}

    defaults:
      run:
        shell: pwsh # use powershell as default shell for all steps

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ********** .NET Project **********
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
        env:
          # set 'DOTNET_INSTALL_DIR' env to fix: Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 'C:\ProgramFiles\dotnet\dotnet.exe' because it is being used by another process."
          DOTNET_INSTALL_DIR: "../../_tool/.dotnet"

      - name: Restore .NET dependencies
        run: dotnet restore "./src/tracker-api.csproj"

      - name: Build .NET
        run: dotnet build "./src/tracker-api.csproj" --no-restore

      - name: Publish .NET
        # publish for 'all runtimes' (need to make sure .NET runtime is properly installed on target machine)
        run: dotnet publish "./src/tracker-api.csproj" -c Release -o ./publish --no-restore

      # ********** Release Drafter **********
      # TODO: prevent creating a release if there are no changes !!!
      - uses: release-drafter/release-drafter@master
        id: release-drafter
        with:
          publish: true
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ********** Prepare release folder & zip it **********
      - name: Create release folder
        run: New-Item -ItemType Directory -Force -Path "./tracker-api-${{ steps.release-drafter.outputs.name }}"

      - name: Copy .NET publish folder to release folder
        run: cp -r "./publish" "./tracker-api-${{ steps.release-drafter.outputs.name }}/"

      - name: Copy docker files (excluding dev) to release folder
        run: |
          if ("${{ runner.os }}" -eq 'Linux') {
            # 'rsync' is not a built-in command in Windows PowerShell
            rsync -va --exclude="*.dev*" "./docker-files" "./tracker-api-${{ steps.release-drafter.outputs.name }}/"
          }
          else {
            # '-Exclude' is not a valid option for the cp command on Linux.
            cp -r "./docker-files" "./tracker-api-${{ steps.release-drafter.outputs.name }}/" -Exclude "*.dev*"
          }

      - name: Zip release folder
        # use /* in 'src path' to zip only the content of the folder, not the folder itself (avoid double folder in zip)
        run: Compress-Archive -Path "./tracker-api-${{ steps.release-drafter.outputs.name }}/*" -DestinationPath "./tracker-api-${{ steps.release-drafter.outputs.name }}.zip"

      # ********** Upload zipped release to Artifact / Store zipped release in local temp folder **********

      - name: Upload release to Artifact
        # upload to artifact only if running on 'ubuntu-latest'
        if: ${{ inputs.build-release-runner == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: "tracker-api-${{ steps.release-drafter.outputs.name }}.zip"
          path: "./tracker-api-${{ steps.release-drafter.outputs.name }}.zip"
          retention-days: 1
          if-no-files-found: error

      - name: Move release folder to 'temp/uploads' folder
        if: ${{ inputs.build-release-runner != 'ubuntu-latest' }}
        run: |
          # STEP 1: Create "temp/uploads" folder if it doesn't exist
          if (!(Test-Path -Path "./temp/uploads")) {
            New-Item -ItemType Directory -Force -Path "./temp/uploads"
          }

          # STEP 2: Move release folder to "temp/uploads" folder
          mv "./tracker-api-${{ steps.release-drafter.outputs.name }}.zip" "./temp/uploads/tracker-api-${{ steps.release-drafter.outputs.name }}.zip"

    # Set job output to be used in next job
    outputs:
      release-file-name: "tracker-api-${{ steps.release-drafter.outputs.name }}.zip"

  # ---------- JOB ----------
  upload-release-to-s3:
    needs: build-release
    uses: Star-Communications/centralized-repo/.github/workflows/upload-s3.yml@master
    with:
      runs-on: ${{ inputs.build-release-runner }}
      # if running on 'ubuntu-latest', upload file will be downloaded from artifact (upload folder path won't be used)
      upload-file-path: "./temp/uploads/${{ needs.build-release.outputs.release-file-name}}"
      s3-bucket-name: "sc-releases-bucket"
      s3-prefix: "tracker-api"
    secrets:
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::977628787421:role/oidc-release-upload-role"
