# This wrorkflow checks if the PR branch name is following the convention defined in the workflow file.

# If PR branch name doesn't follow specified naming conventions, the workflow fails.

# The workflow takes 2 inputs:
#   1. PR branch name
#   2. Additional branch names to add to naming conventions (comma separated)

name: Branch name convention

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Type of runner(s) to use (comma separated)"
        type: string
        required: false
        default: "ubuntu-latest"

      branch-name:
        description: "Branch name"
        type: string
        required: true

      additional-branch-names:
        description: "Additional branch names (comma separated)"
        type: string
        required: false
        default: ""

jobs:
  branch-name-convention:
    runs-on: ${{ inputs.runs-on }}

    steps:
      # concatenate additional branch names to convention branch names defined below ('dependabot' & 'bump' are used by dependabot)
      - name: Set convention branch names
        id: setConventionBranchNames
        env:
          OS: ${{ runner.os}}
          CONVENTIONAL_BRANCH_NAMES: "break,feat,fix,deps,docs,enhance,refactor,test,cicd,other,dependabot,bump"
        run: |
          echo "Additional branch names: ${{ inputs.additional-branch-names }}"
          # if additional branch names are provided, concatenate them to "convention branch names"
          if (${{ inputs.additional-branch-names }}) {
              $CONVENTIONAL_BRANCH_NAMES = "$CONVENTIONAL_BRANCH_NAMES,${{ inputs.additional-branch-names }}"
          }
          # split by comma and remove spaces, then join with |
          $CONVENTIONAL_BRANCH_NAMES = ($CONVENTIONAL_BRANCH_NAMES -replace ',', '|').Trim()
          echo "Convention branch names: $CONVENTIONAL_BRANCH_NAMES"
          if ("$OS" -eq "Windows") {
              echo "conventionBranchNames=$CONVENTIONAL_BRANCH_NAMES" >> "$env:GITHUB_OUTPUT"
          } else {
              echo "conventionBranchNames=$CONVENTIONAL_BRANCH_NAMES" >> "$GITHUB_OUTPUT"
          }

      - name: Check branch name is following convention
        env:
          CONVENTIONAL_BRANCH_NAMES: "${{ steps.setConventionBranchNames.outputs.conventionBranchNames }}"
        run: |
          echo "Branch name is ${{ inputs.branch-name }}"
          if ("${{ inputs.branch-name }}" -match "^($CONVENTIONAL_BRANCH_NAMES)/.*") {
              echo "Branch name is following convention"
          } else {
              echo "Branch name is NOT following naming convention"
              echo "Branch name should start with one of the following: $CONVENTIONAL_BRANCH_NAMES"
              exit 1
          }
