# This wrorkflow checks if the PR branch name is following the convention defined in the workflow file.

# If PR branch name doesn't follow specified naming conventions, the workflow fails.

# The workflow takes 2 inputs:
#   1. PR branch name
#   2. Additional branch names to add to naming conventions (comma separated)

name: Branch name convention

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Type of runner(s) to use (comma separated)"
        type: string
        required: false
        default: "ubuntu-latest"

      branch-name:
        description: "Branch name"
        type: string
        required: true

      additional-branch-names:
        description: "Additional branch names (comma separated)"
        type: string
        required: false
        default: ""

jobs:
  branch-name-convention:
    runs-on: ${{ inputs.runs-on }}

    steps:
      # concatenate additional branch names to convention branch names defined below ('dependabot' & 'bump' are used by dependabot)
      # TODO: add check to validate that additional branch names are not already part of convention branch names & are in correct format
      - name: Set convention branch names
        id: setConventionBranchNames
        shell: pwsh
        env:
          CONVENTIONAL_BRANCH_NAMES: "break,feat,fix,deps,docs,enhance,refactor,test,cicd,other,dependabot,bump"
        run: |
          echo "Additional branch names: ${{ inputs.additional-branch-names }}"
          # if additional branch names are provided, concatenate them to "convention branch names"
          if (-not [string]::IsNullOrEmpty("${{ inputs.additional-branch-names }}")) {
              $env:CONVENTIONAL_BRANCH_NAMES = "$env:CONVENTIONAL_BRANCH_NAMES,${{ inputs.additional-branch-names }}"
          }
          # replace ',' with '|' & remove leading & trailing spaces
          $regexBranchNameTemp=$env:CONVENTIONAL_BRANCH_NAMES.replace(',', '|').Trim()
          echo "Convention branch names (regex): $regexBranchNameTemp"
          echo "regexBranchNames=$regexBranchNameTemp" >> "$env:GITHUB_OUTPUT"

      - name: Check branch name is following convention
        shell: pwsh
        env:
          REGEX_BRANCH_NAMES: "${{ steps.setConventionBranchNames.outputs.regexBranchNames }}"
        run: |
          echo "Branch name is ${{ inputs.branch-name }}"
          if ("${{ inputs.branch-name }}" -match "^($REGEX_BRANCH_NAMES)/.*") {
              echo "Branch name is following convention"
          } else {
              echo "Branch name is NOT following naming convention"
              echo "Branch name should start with one of the following: $REGEX_BRANCH_NAMES"
              exit 1
          }
