# Run pre-release checks before running the build release workflow
name: pre-release-checks

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Type of runner(s) to use (comma separated)"
        type: string
        required: false
        default: "yasmin-machine-org"

    outputs:
      is-new-release-job-output:
        description: "Flag to indicate if current commit is a new release"
        value: ${{ jobs.pre-release-checks.outputs.is-new-release-output }}

jobs:
  pre-release-checks:
    runs-on: ${{ inputs.runs-on }}

    outputs:
      is-new-release-output: ${{ steps.check-tag.outputs.is-new-release-step-output }}

    steps:
      # prevent running 'build-release' job (checkout our code) on a customer's runner
      - name: Verify runner environment
        shell: pwsh
        run: |
          # Fail if runner is not 'ubuntu-latest' or 'yasmin-machine-org'
          # if ('${{ inputs.runs-on }}' -notin @('ubuntu-latest', 'yasmin-machine-org')) {
          #   echo "Runner must be either 'ubuntu-latest' or 'yasmin-machine-org'"
          #   exit 1
          # }

          echo On "Runner '${{ inputs.runs-on }}'."

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if current commit is already tagged
        shell: pwsh
        id: check-tag
        run: |
          # STEP 1: Get latest tag
          $latestTag = git describe --tags --abbrev=0

          # STEP 2: Get current commit hash
          $currentCommit = git rev-parse HEAD

          # STEP 3: Get current commit tag (if tagged, else '2>&1' will return the error message)
          $currentCommitTag=$(git describe --tags --abbrev=0 --exact-match "$currentCommit" 2>&1)
          echo "currentCommitTag = $currentCommitTag"

          # STEP 4: Compare $latestTag with $currentCommitTag
          if ($latestTag -eq $currentCommitTag) {
            echo "Current commit is already tagged"
            echo "is-new-release-step-output=false" >> $env:GITHUB_OUTPUT
            echo "is-new-release-step-output = false"
          }
          else {
            echo "Current commit is not tagged"
            echo "is-new-release-step-output=true" >> $env:GITHUB_OUTPUT
            echo "is-new-release-step-output = true"
          }

          # Add 'exit 0' to avoid step failure when '--exact-match' return process exit code 1
          exit 0;
