name: cd-upload-s3

on:
  workflow_call:
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: "ARN of the AWS role to assume"
        required: true

    inputs:
      runs-on:
        description: "Type of runner(s) to use (comma separated)"
        type: string
        required: false
        default: "ubuntu-latest"

      release-artifact-name:
        description: "Name of the artifact (release files) to download"
        type: string
        required: true

      s3-bucket-name:
        description: "Name of the S3 bucket to upload to"
        type: string
        required: true

      s3-prefix:
        description: "Name of the S3 bucket prefix (subfolder) to upload to"
        type: string
        required: true

permissions:
  id-token: write # This is required for OIDC requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  upload-release:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Log runner label(s)
        run: |
          echo "runs-on: ${{ inputs.runs-on }}"

      # ********** Download release file from artifact **********
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.release-artifact-name }}
          path: ./download

      # ********** Upload to S3 **********
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: UploadReleaseToS3
          aws-region: eu-central-1

      # Set shell:pwsh so that cmds below work on both Windows & Linux runners.
      # (NOTE: Windows runners can't access bash shell - "Access is denied.")

      # NOT NEEDED?? As release-drafter step above creates a new version even if no new changes are found.
      - name: Check if release version is already in S3
        shell: pwsh
        run: |
          echo "Release folder: ${{ inputs.release-artifact-name }}"
          $releaseObjects = @(aws s3api list-objects-v2 --bucket "${{ inputs.s3-bucket-name }}" --prefix "${{ inputs.s3-prefix }}" --query "Contents[?contains(Key, '${{ inputs.release-artifact-name }}.zip') || contains(Key, '${{ inputs.release-artifact-name }}-latest.zip')].Key" --output text)
          echo "S3 Objects with same release folder name: $releaseObjects"
          if ($releaseObjects -ne "None" -and $releaseObjects) {
            throw "Release folder already exists in S3."
          }

      - name: Remove '-latest' suffix from any S3 object name
        shell: pwsh
        run: |
          $latestObjectKeys = @(aws s3api list-objects-v2 --bucket "${{ inputs.s3-bucket-name }}" --prefix "${{ inputs.s3-prefix }}" --query 'Contents[?ends_with(Key, `-latest.zip`)].Key' --output text)
          echo "S3 Objects containing 'latest': $latestObjectKeys"
          if (-not [string]::IsNullOrEmpty($latestObjectKeys) -and $releaseObjects -ne "None") {
            $latestObjectKeys = $latestObjectKeys.Split()
            foreach ($object in $latestObjectKeys) {
              $newObjName = $object.Replace("${{ inputs.s3-prefix }}/","").Replace("-latest.zip",".zip")
              echo "Old object name: $object"
              echo "New object name: $newObjName"
              aws s3 mv "s3://${{ inputs.s3-bucket-name }}/$object" "s3://${{ inputs.s3-bucket-name }}/${{ inputs.s3-prefix }}/$newObjName"
            }
          } else {
            echo "No objects containing '-latest' found in S3 bucket."
          }

      - name: Upload new release folder (zipped) to S3 (add '-latest' suffix)
        run: aws s3 cp "./download/${{ inputs.release-artifact-name }}.zip" "s3://${{ inputs.s3-bucket-name }}/${{ inputs.s3-prefix }}/${{ inputs.release-artifact-name }}-latest.zip"
